# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  e2e_tests:
    name: e2e_tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout awm-relayer repository
        uses: actions/checkout@v4
        
      - name: Set Go version
        run: |
          source ./scripts/versions.sh
          echo GO_VERSION=$GO_VERSION >> $GITHUB_ENV
          echo SUBNET_EVM_VERSION=$SUBNET_EVM_VERSION >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout subnet-evm repository
        uses: actions/checkout@v4
        with:
          repository: ava-labs/subnet-evm
          ref: v0.5.8 # TODO set with env.SUBNET_EVM_VERSION

      - name: Install AvalancheGo Release
        run: BASEDIR=/tmp/e2e-test AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego ./scripts/install_avalanchego_release.sh

      - name: Build Subnet-EVM Plugin Binary
        run: ./scripts/build.sh /tmp/e2e-test/avalanchego/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy

      - name: Checkout awm-relayer repository
        uses: actions/checkout@v4

      - name: Run E2E Tests
        run: AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego DATA_DIR=/tmp/e2e-test/data ./scripts/e2e_test.sh
